# Generated by Django 5.0.1 on 2024-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('app_url', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('img', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
